# Generated by Django 4.2 on 2023-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
